name: Pipeline

# Déclenchement de la pipeline lors d'une Pull Request (PR) ou Merge Request (MR) vers la branche principale
on:
  pull_request:
    branches:
      - main

jobs:
  # Job pour l'intégration continue (CI)
  ci:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up Git config
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true

      # Étape 2 : Installer les dépendances (par exemple, pour un projet Node.js)
      - name: Install dependencies
        run: |
          npm install

      # Étape 3 : Vérification du formatage du code (par exemple, avec Prettier)
      - name: Check code formatting
        run: |
          npm run prettier


      # Étape 4 : Lancer les linters pour vérifier la qualité du code (par exemple, avec ESLint)
      - name: Lint code
        run: |
          npm run lint

      # Étape 5 : Lancer les tests unitaires
      - name: Run unit tests
        run: |
          npm test

  # Job pour le déploiement continu (CD)
  cd:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: ci
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Déploiement vers Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
